apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "easyx.fullname" . }}-admin
  labels:
    {{- include "easyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      {{- include "easyx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin
  template:
    metadata:
      labels:
        {{- include "easyx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: admin
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "easyx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: admin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "easyx.image" (dict "root" . "image" .Values.admin.image) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.admin.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.admin.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.admin.env.PORT | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
