{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "easyx.fullname" . }}
  labels:
    {{- include "easyx.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    # API Ingress
    - host: {{ .Values.ingress.hosts.api.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.api.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "easyx.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    # Web Ingress
    - host: {{ .Values.ingress.hosts.web.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.web.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "easyx.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    # Admin Ingress
    - host: {{ .Values.ingress.hosts.admin.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.hosts.admin.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "easyx.fullname" $ }}-admin
                port:
                  number: {{ $.Values.admin.service.port }}
          {{- end }}
{{- end }}
