apiVersion: v1
kind: Service
metadata:
  name: {{ include "easyx.fullname" . }}-api
  labels:
    {{- include "easyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "easyx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "easyx.fullname" . }}-web
  labels:
    {{- include "easyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "easyx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "easyx.fullname" . }}-admin
  labels:
    {{- include "easyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "easyx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
